name: 11-inputs

on:
  workflow_dispatch:
    inputs:
      dry-on:
        type: boolean
        description: Skip deployment and only print build output
        default: true
      target:
        type: environment
        description: Which environment the workflow will target
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building from tag ${{ inputs.tag }}"

  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-on }}
    environment: ${{ inputs.target }}
    needs: build
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }} environment"
