name: 12-Working with outputs

on:
    workflow_dispatch:
        inputs:
            build_status:
                type: choice
                options:
                  - success
                  - failure
                default: success

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            build_output: ${{ steps.build.outputs.status }}
        steps:
          - name: Print GITHUB_OUTPUT path
            run: echo "$GITHUB_OUTPUT"

          - name: Build
            id: build
            run: |
                echo "$GITHUB_OUTPUT"
                echo "status=${{ inputs.build_status }}" >> $GITHUB_OUTPUT

    deploy:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ needs.build.outputs.build_output == 'success' }}
        steps:
          - name: Deploy
            run: echo "Deploying"
